exports.mock = 
  {
    firstVisit: [
      {
        id: 1,
        title: "McMonnies Dry Eye Questionnaire Index",
        sortOrder: 1,
        surveyPages: [
          {
            id: 1,
            pageNumber: 1,
            titleIcelandic: "",
            descriptionIcelandic: "",
            titleEnglish: "",
            descriptionEnglish: "",
            questions: [
              {
                id: 1,
                titleIcelandic: "Hvert er kyn þitt?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 1,
                options: [
                  {
                    id: 1,
                    titleIcelandic: "Karl",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 2,
                    titleIcelandic: "Kona",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 134,
                    titleIcelandic: "Annað",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
              {
                id: 2,
                titleIcelandic: "Hver er aldur þinn?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 2,
                options: [
                  {
                    id: 3,
                    titleIcelandic: "Undir 25 ára",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 4,
                    titleIcelandic: "25-45 ára",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 5,
                    titleIcelandic: "Yfir 45 ára",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
              {
                id: 3,
                titleIcelandic: "Notar þú snertilinsur?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 3,
                options: [
                  {
                    id: 6,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 7,
                    titleIcelandic: "Harðar linsur",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 8,
                    titleIcelandic: "Mjúkar linsur",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
              {
                id: 4,
                titleIcelandic:
                  "Hefur þú áður notað augndropa við augnþurrki eða fengið aðra meðferð?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 4,
                options: [
                  {
                    id: 9,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 10,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 11,
                    titleIcelandic: "Veit ekki",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
              {
                id: 5,
                titleIcelandic:
                  "Hefur þú áður fundið fyrir einhverjum þessara einkenna?",
                titleEnglish: "",
                type: "checkbox",
                mandatory: false,
                pageNumber: 1,
                sortOrder: 5,
                options: [
                  {
                    id: 12,
                    titleIcelandic: "Særindi",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 13,
                    titleIcelandic: "Kláði",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 14,
                    titleIcelandic: "Þurrkur",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 15,
                    titleIcelandic: "Sandur í augum",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 16,
                    titleIcelandic: "Sviði",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                ],
              },
              {
                id: 6,
                titleIcelandic: "Hversu oft hefur þú haft þessi einkenni?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 1,
                sortOrder: 6,
                options: [
                  {
                    id: 17,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 18,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 19,
                    titleIcelandic: "Oft",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 20,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                ],
              },
              {
                id: 7,
                titleIcelandic:
                  "Finnst þér augun þín vera óvenjulega næm fyrir ryki, mengun, loftræstingu eða hitakerfum?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 7,
                options: [
                  {
                    id: 21,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 22,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 23,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
              {
                id: 8,
                titleIcelandic:
                  "Verða augun þín fljótt rauð og ert þegar þú ferð í sundlaugar?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 8,
                options: [
                  {
                    id: 24,
                    titleIcelandic: "Á ekki við",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 25,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 26,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 27,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                ],
              },
              {
                id: 9,
                titleIcelandic:
                  "Færð þú þurr og rauð augu eftir að hafa drukkið áfengi daginn áður?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 9,
                options: [
                  {
                    id: 28,
                    titleIcelandic: "Á ekki við",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 29,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 30,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 31,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                ],
              },
              {
                id: 10,
                titleIcelandic: "Þjáist þú af liðagigt",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 10,
                options: [
                  {
                    id: 32,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 33,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 34,
                    titleIcelandic: "Óviss",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
              {
                id: 11,
                titleIcelandic:
                  "Þjáist þú af þurrki í nefi, munni, hálsi, brjósti eða leggöngum?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 11,
                options: [
                  {
                    id: 35,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 36,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 37,
                    titleIcelandic: "Oft",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 38,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                ],
              },
              {
                id: 12,
                titleIcelandic: "Ert þú með van/ofstarfsemi á skjaldkirtli?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 12,
                options: [
                  {
                    id: 39,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 40,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 41,
                    titleIcelandic: "Óviss",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
              {
                id: 13,
                titleIcelandic:
                  "Veist þú til þess að þú sofir með augun að hluta til opin?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 13,
                options: [
                  {
                    id: 42,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 43,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 44,
                    titleIcelandic: "Óviss",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
              {
                id: 14,
                titleIcelandic:
                  "Eru augun þín þrútin, ert og rauð þegar þú vaknar?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 14,
                options: [
                  {
                    id: 45,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 46,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 47,
                    titleIcelandic: "Óviss",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 2,
        title: "Ocular Surface Diseast Index",
        sortOrder: 2,
        surveyPages: [
          {
            id: 2,
            pageNumber: 1,
            titleIcelandic:
              "Hafa einkenni frá augum haft áhrif á eftirtöldum einkennum síðastliðna viku?",
            descriptionIcelandic: "Merktu við þann möguleika sem á best við",
            titleEnglish: "",
            descriptionEnglish: "",
            questions: [
              {
                id: 15,
                titleIcelandic: "Ljósfælni?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 1,
                sortOrder: 1,
                options: [
                  {
                    id: 48,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 49,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 50,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 51,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 52,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 53,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 16,
                titleIcelandic: "Tilfinningu um sand í augum?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 1,
                sortOrder: 2,
                options: [
                  {
                    id: 54,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 55,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 56,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 57,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 58,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 59,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 17,
                titleIcelandic: "Særindum eða verkjum í augum?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 1,
                sortOrder: 3,
                options: [
                  {
                    id: 60,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 61,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 62,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 63,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 64,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 65,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 18,
                titleIcelandic: "Móðusjón?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 1,
                sortOrder: 4,
                options: [
                  {
                    id: 66,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 67,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 68,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 69,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 70,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 71,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 19,
                titleIcelandic: "Versnun sjónar?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 1,
                sortOrder: 5,
                options: [
                  {
                    id: 72,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 73,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 74,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 75,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 76,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 77,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
            ],
          },
          {
            id: 3,
            pageNumber: 2,
            titleIcelandic:
              "Hafa einkenni frá augum haft áhrif á eftirtalin atriði síðastliðna viku?",
            descriptionIcelandic: "Merktu við þann möguleika sem á best við",
            titleEnglish: "",
            descriptionEnglish: "",
            questions: [
              {
                id: 20,
                titleIcelandic: "Lestrargetu?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 2,
                sortOrder: 1,
                options: [
                  {
                    id: 78,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 79,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 80,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 81,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 82,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 83,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 21,
                titleIcelandic: "Akstur í myrkri",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 2,
                sortOrder: 2,
                options: [
                  {
                    id: 84,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 85,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 86,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 87,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 88,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 89,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 22,
                titleIcelandic:
                  "Skjávinnu (t.d. Snjallsíma, spjaltölvur og tölvuskjái)",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 2,
                sortOrder: 3,
                options: [
                  {
                    id: 90,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 91,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 92,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 93,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 94,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 95,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 23,
                titleIcelandic: "Sjónvarpsáhorf",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 2,
                sortOrder: 4,
                options: [
                  {
                    id: 96,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 97,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 98,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 99,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 100,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 101,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
            ],
          },
          {
            id: 4,
            pageNumber: 3,
            titleIcelandic:
              "Hefur þú fundið fyrir óþægindum í augum við einhverra þessara kringumstæðna?",
            descriptionIcelandic: "Merktu við þann möguleika sem á best við",
            titleEnglish: "",
            descriptionEnglish: "",
            questions: [
              {
                id: 24,
                titleIcelandic: "Þurrkeinkennum í vindi?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 3,
                sortOrder: 1,
                options: [
                  {
                    id: 102,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 103,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 104,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 105,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 106,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 107,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 25,
                titleIcelandic:
                  "Einkennum vegna loftþurrks, s.s. við upphitun eða loftræstingu?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 3,
                sortOrder: 2,
                options: [
                  {
                    id: 108,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 109,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 110,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 111,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 112,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 113,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
              {
                id: 26,
                titleIcelandic:
                  "Þurreinkenni vegna loftkælingu (air condition í bíl, loftræsting á vinnustað)?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: false,
                pageNumber: 3,
                sortOrder: 3,
                options: [
                  {
                    id: 114,
                    titleIcelandic: "Alltaf",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                  {
                    id: 115,
                    titleIcelandic: "Oftast",
                    titleEnglish: "",
                    sortOrder: 2,
                  },
                  {
                    id: 116,
                    titleIcelandic: "Stundum",
                    titleEnglish: "",
                    sortOrder: 3,
                  },
                  {
                    id: 117,
                    titleIcelandic: "Sjaldan",
                    titleEnglish: "",
                    sortOrder: 4,
                  },
                  {
                    id: 118,
                    titleIcelandic: "Aldrei",
                    titleEnglish: "",
                    sortOrder: 5,
                  },
                  {
                    id: 119,
                    titleIcelandic: "Spurning á ekki við",
                    titleEnglish: "",
                    sortOrder: 6,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 3,
        title: "Sjögrens List",
        sortOrder: 3,
        surveyPages: [
          {
            id: 5,
            pageNumber: 1,
            titleIcelandic: "",
            descriptionIcelandic: "Merktu við þann möguleika sem á best við",
            titleEnglish: "",
            descriptionEnglish: "",
            questions: [
              {
                id: 27,
                titleIcelandic:
                  "Hefur þú fengið greininguna Sjögrens sjúkdómur?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 1,
                options: [
                  {
                    id: 120,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 0,
                  },
                  {
                    id: 121,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: 28,
                titleIcelandic:
                  "Hefur þú haft viðvarandi og hamlandi augnþurrk í meira en 3 mánuði?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 2,
                options: [
                  {
                    id: 122,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 0,
                  },
                  {
                    id: 123,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: 29,
                titleIcelandic:
                  "Færð þú endurtekna tilfinningu um sand í augum?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 3,
                options: [
                  {
                    id: 124,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 0,
                  },
                  {
                    id: 125,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: 30,
                titleIcelandic: "Notar þú gervitár oftar en þrisvar á dag?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 4,
                options: [
                  {
                    id: 126,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 0,
                  },
                  {
                    id: 127,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: 31,
                titleIcelandic:
                  "Hefur þú fundið fyrir munnþurrki daglega í meira en 3 mánuði?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 5,
                options: [
                  {
                    id: 128,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 0,
                  },
                  {
                    id: 129,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: 32,
                titleIcelandic:
                  "Hefur þú fengið endurtekið eða viðvarandi bólgur í munnvatnskirtla sem fullorðin(n)",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 6,
                options: [
                  {
                    id: 130,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 0,
                  },
                  {
                    id: 131,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: 33,
                titleIcelandic:
                  "Hefur þú vanið þig á að drekka með mat til að eiga auðveldara með að kyngja?",
                titleEnglish: "",
                type: "radiogroup",
                mandatory: true,
                pageNumber: 1,
                sortOrder: 7,
                options: [
                  {
                    id: 132,
                    titleIcelandic: "Já",
                    titleEnglish: "",
                    sortOrder: 0,
                  },
                  {
                    id: 133,
                    titleIcelandic: "Nei",
                    titleEnglish: "",
                    sortOrder: 1,
                  },
                ],
              },
            ],
          },
        ],
      },
    ]
  }